version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/FlightSearchApp
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: /AWS/scripts/preinstall.sh
      timeout: 120
      runas: ec2-user
  AfterInstall:
    - location: /AWS/scripts/build.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: /AWS/scripts/start.sh
      timeout: 120
      runas: ec2-user